# Generated by Django 4.1 on 2022-11-27 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_restaurant_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_user', models.TextField()),
                ('itemname', models.TextField()),
                ('itemcost', models.TextField()),
                ('itemcategory', models.TextField()),
                ('aboutitem', models.TextField()),
                ('user_id', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant_details',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='restaurantcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_item', models.TextField()),
                ('category_item_img', models.ImageField(blank=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.TextField()),
                ('restaurant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
