# Generated by Django 4.1 on 2022-12-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_details_alter_restaurant_details_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurants_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_user', models.TextField()),
                ('category_item', models.TextField()),
                ('category_item_img', models.ImageField(blank=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.TextField()),
            ],
        ),
    ]
