# Generated by Django 4.2 on 2023-05-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookeditem_code_bookeditem_finalbill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_code_for_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True)),
                ('code', models.TextField(blank=True)),
                ('additional', models.TextField(blank=True)),
            ],
        ),
    ]
