# Generated by Django 4.2 on 2023-05-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_code_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookeditem',
            name='accepted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order_history',
            name='accepted',
            field=models.TextField(blank=True),
        ),
    ]
