# Generated by Django 4.2 on 2023-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_bookeditem_accepted_order_history_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookeditem',
            name='confirmorder_by_restaurant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookeditem',
            name='item_not_yet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookeditem',
            name='order_rejected',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order_history',
            name='confirmorder_by_restaurant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order_history',
            name='item_not_yet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order_history',
            name='order_rejected',
            field=models.TextField(blank=True),
        ),
    ]
