# Generated by Django 4.2 on 2023-05-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_status',
            name='item_id',
            field=models.TextField(blank=True),
        ),
    ]
